name: Deploy node on ExCloud Ec2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Deploy to ExCloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 210.79.128.197
          username: ubuntu
          key: ${{secrets.SSH_KEY}}
          port: 22
          script: |
            cd /home/ubuntu/nodeServer
            git pull
            npm install
            pm2 restart all