name: Deploy node with ExCloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Deploy to ExCloud
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 210.79.128.197
          username: ubuntu
          key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAv8D2J3gtv0v8goqsAjydt80mY9OdZR9sV2YU2SlSGQ server-dubeyjags@gmail.com
          port: 22
          script: |
            cd /home/ubuntu/nodeServer
            git pull
            npm install
            pm2 restart all